name: CI-CD Pipeline

# Whenever someone pushes code to the main branch
# GitHub automatically starts this pipeline
on:
  push:
    branches:
      - main
      
#single job named build-test-deploy
#Runs on a fresh Ubuntu virtual machine
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    #Downloads your GitHub repo into the runner
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        pip install pytest pyspark
    #Executes pwd and returns the current folder path
    - name: Run Tests
      run: |
        export PYTHONPATH=$(pwd)
        pytest tests/

    - name: Install Databricks CLI
      run: |
        pip install databricks-cli

    - name: Deploy Notebook
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks workspace import_dir notebooks /Shared/devops_demo --overwrite

    - name: Create Databricks Job (JSON)
      env:
        DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
        DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      run: |
        databricks jobs reset --job-id 841027682634122 --json-file job_medallion.json

#Push to main
#      ↓
#GitHub Actions starts
#     ↓
#Install Python
#      ↓
#Install dependencies
#      ↓
#Run unit tests
#      ↓
#Deploy notebooks to Databricks
#     ↓
#Update Databricks Job using JSON